
<!--PARTIAL VIEW CREATED FOR RENDERING PRELOADER AREA-->

<?php
  /* getting PATH of image to render */ 
  $pathLogo =  $this->pathLogo;
?>

<!-- preloader area start -->
<div class="preloader" id="preloader">
   <div class="preloader-inner">
       <div class="lds-ripple">
       <div></div>
       <div class="img-wrapper">
           <img src="<?=$pathLogo?>" height="50" alt="CTP lOGO"/>
       </div>
       </div>
   </div>
</div> 

 <!-- support bar area start **********************-->
<div class="support-bar-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="left-content-area"><!-- left content area -->
                    <ul>
                        <li>Mon – Fri: 8.30 – 17.35</li>
                        <li>Saturday, Sunday: Closed </li>
                        <li>Emergency: 24hr / 7days</li>
                    </ul>
                </div><!-- //.left conten tarea -->
                <div class="right-content-area"><!-- left content area -->
                    <ul>
                        <li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
                        <li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
                        <li><a href="#"> <i class="fab fa-instagram"></i> </a></li>
                        <li><a href="#"> <i class="fab fa-linkedin-in"></i> </a></li>
                    </ul>
                </div><!-- //.left contentarea -->
            </div>
        </div>
    </div>
</div>  <!-- support bar area -->