<?php
    $this->headTitle('Sign in');

    $this->mainMenu()->setActiveItemId('login');

    $form->get('email')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Email address',
        'required' => true,
        'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);

    $form->get('password')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Password',
        'required' => true,
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);
    //$form->prepare();
?>

<!--************************************** HTML RENDER ********************************** -->
<div class="row label-info1">
    <div class="col-md-offset-4 col-md-3">
        <div class="panel panel-primary">
            <div class="panel-heading"> <span class="">SIGN IN</span></div>            
            <div class="panel-body ">
                <form class="form-signin" method="post">            
                    <!-- checking if there was some error while -->
                    <?php if ($isLoginError): ?>
                        <div class="alert alert-warning" role="alert">
                            Incorrect login and/or password. 
                            <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                        </div>
                    <?php endif; ?>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>                        
                        <?= $this->formElement($form->get('email')); ?>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>                        
                        <?= $this->formElement($form->get('password')); ?>
                    </div>    
                    <div class="checkbox">
                        <label>
                            <?= $this->formElement($form->get('remember_me')); ?> Remember me
                        </label>
                    </div>
                    <?= $this->formElement($form->get('redirect_url')); ?>
                    <?= $this->formElement($form->get('csrf')) ?>
                    <button class="btn btn-lg btn-info btn-block btn-sm" type="submit">Sign in</button>
                </form>
            </div>
        </div> <!-- panel primary -->
    </div>
</div>