<?php
    $this->headTitle('Sign in');

    $this->mainMenu()->setActiveItemId('login');

    $form->get('email')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Email address',
        'required' => true,
        'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);

    $form->get('password')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Password',
        'required' => true,
        ])
        ->setLabelAttributes([
            'class' => ''
        ]);
    $form->prepare();
?>

<!--************************************** HTML RENDER ********************************** -->
 
    <br> 
    <div class="alert alert-warning">
        <img class="header-img" src="<?= $this->basePath().'/img/LOGO.PNG' ?>" height="80" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>
        <h3 class="subtitle">USER LOGIN </h3>
   
        <form class="" method="post">            
            <!-- checking if there was some error while -->
            <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect login and/or password. 
                    <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                </div>
            <?php endif; ?>

            <div class="form-group">
                <i class="fas fa-user"></i> 
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>                
            </div>
            <div class="form-group">
                <i class="fas fa-lock"></i>                
                <?= $this->formElement($form->get('password')); ?>
            </div>    
            <div>
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> Remember me
                </label>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <button class="submit-btn" type="submit">Sign in</button>
        </form>
</div>
