<?php
    $this->headTitle("Not Authorized");
    
    $this->pageBreadcrumbs()->setItems([
                    'Home'=>$this->url('home'),
                    'Not Authorized'=>$this->url('users')
    ]);
?>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 single-service-item"> 
            <h3 class="title">Sorry, you have no permission to see this page.</h3>
            
        </div>
    </div>
</div>
