
<!-- error 404 page content area start -->
<section class="error-404-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="error-content-inner">
                    <div class="img-wrapper">
                        <img src="assets/img/404.jpg" alt="error image">
                    </div>
                    <div class="content">
                        <h4 class="title">Oops!!, Page not found</h4>
                        <p>The page or content you are looking for cannot be found! Please search or go back to home.</p>
                        
                        <div class="btn-wrapper">
                            <a href="<?=$this->url('home'); ?>" class="boxed-btn">Go Back To Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- error 404 page content area end -->

  