<?php
    $this->headTitle('Change Password');

    $this->mainMenu()->setActiveItemId('users');
    
    //We need to change the second root  when the user is not administrator
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Settings'=>$this->url('application', ['action'=>'settings']),
                'Change Password'=>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
                ]);

    //getting  form fields with its respectevely attributes 
    if ($showoldpassword !='reset') {
        $form->get('old_password')->setAttributes([
            'class'=>'form-control', 
            'placeholder'=>'Enter old password'
            ]);
    }
    
    $form->get('new_password')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter new password'
        ]);

    $form->get('confirm_new_password')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Re-enter new password'
        ]);

    $form->get('submit')->setAttributes(['class'=>'submit-btn']);
    $form->get('submit')->setAttributes(['value' =>'Reset Password']);
    
    $form->prepare();
?>

<!--******************************************** RENDERING HTML ************************************************-->
<div class="row justify-content-center">
    <div class="col-lg-3 single-service-item ">                 
        <p class="checklist"><i class="base-color fa fa-user"></i>
            <?= $this->escapeHtml($user->getEmail()) ?>
        </p>            
        <br>
        <!-- Open Form Tag -->
        <?= $this->form()->openTag($form); ?>
            <!-- EDIT: OLD PASSWORD -->
            <div class="form-group">                    
                <?php if ($showoldpassword !='reset'):?>
                    <i class=" fa fa-lock"></i>
                    <?= $this->formLabel($form->get('old_password')); ?>
                    <?= $this->formElement($form->get('old_password')); ?>
                    <?= $this->formElementErrors($form->get('old_password')); ?>       
                <?php endif; ?>
            </div>

            <!-- EDIT: NEW PASSWORD -->
            <div class="form-group">
                <i class=" fa fa-lock"></i>
                <?= $this->formLabel($form->get('new_password')); ?>
                <?= $this->formElement($form->get('new_password')); ?>
                <?= $this->formElementErrors($form->get('new_password')); ?>                  
            </div>

            <!-- EDIT: CONFIRM NEW PASSWORD -->
            <div class="form-group">
                <i class=" fa fa-lock"></i>
                <?= $this->formLabel($form->get('confirm_new_password')); ?>
                <?= $this->formElement($form->get('confirm_new_password')); ?>
                <?= $this->formElementErrors($form->get('confirm_new_password')); ?>                  
            </div>

            <!-- CROSS SITE REQUEST FORGERY CHECKING -->    
            <?= $this->formElement($form->get('csrf')); ?>

            <div class="btn-wrapper">
                <?= $this->formElement($form->get('submit')); ?>
            </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>



