<!---------------------------------------------------------------------------------------------------------------
    *** MODULE: USER
    - EDIT.phtml (file) 
    -Description:
        - Rending user's data will been edited 
----------------------------------------------------------------------------------------------------------------->

<?php
    $this->headTitle('Edit User');

    $this->mainMenu()->setActiveItemId('users');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Users'=>$this->url('users'),
                'Edit User'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
                ]);

    $form->get('email')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'user@costex.com'
        ]);

    $form->get('full_name')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Kristov Magic'
        ]);

    $form->get('status')->setAttributes([
        'class'=>'form-control'
        ]);

    $form->get('roles')->setAttributes([
        'class'=>'form-control',        
        ]);

    $form->get('submit')
            ->setAttributes(['class'=>'submit-btn'])
            ->setValue(' Save ');

    $form->prepare();
?>

<!-- *************************************  HTML RENDER: EDIT.PHTM -- USER MODULE ************************** -->


<div class="row justify-content-center">
    <div class="col-md-3 single-service-item"> 
        <h4> EDIT USER</h4>
        
        <!-- form Render : Edit User -->
        <?= $this->form()->openTag($form); ?>        
            <div class="form-group">
                <i class="fa fa-envelope"></i>
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>                  
            </div>

            <div class="form-group">
                <i class="fa fa-user"></i>
                <?= $this->formLabel($form->get('full_name')); ?>
                <?= $this->formElement($form->get('full_name')); ?>
                <?= $this->formElementErrors($form->get('full_name')); ?>                  
            </div>

            <div class="form-group">
                <i class="fa fa-user-check"></i>
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>

            <div class="form-group">
                <i class="fa fa-user-cog"></i>
                <?= $this->formLabel($form->get('roles')); ?>
                <?= $this->formElement($form->get('roles')); ?>
                <?= $this->formElementErrors($form->get('roles')); ?>                  
            </div>

            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElementErrors($form->get('csrf')); ?>
            <?= $this->formElement($form->get('submit')); ?>        
        <?= $this->form()->closeTag(); ?>      
    </div>   <!-- column-md-6 --> 
</div> <!-- MAIN ROW: IT WILL BE RENDERING AS CONTAINER OF THE LAYOUT -->   

