<?php
    $this->headTitle('Edit User');

    $this->mainMenu()->setActiveItemId('users');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Users'=>$this->url('users'),
                'Edit User'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
                ]);

    $form->get('email')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'mojeda@costex.com'
        ]);

    $form->get('full_name')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Kristov Magic'
        ]);

    $form->get('status')->setAttributes([
        'class'=>'form-control'
        ]);

    $form->get('roles')->setAttributes([
        'class'=>'form-control',
        'rows'=> 5, //wrong property
        ]);

    $form->get('submit')
            ->setAttributes(['class'=>'btn btn-primary'])
            ->setValue('Save');

    $form->prepare();
?>

<!-- *************************************  HTML RENDER: EDIT.PHTM -- USER MODULE ************************** -->


<div class="row">
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading"> EDIT USER <span class="alert">  <?= $this->escapeHtml($user->getEmail()) ?></span></div>            
            <div class="panel-body">
                
                <!-- form Render : Edit User -->
                <?= $this->form()->openTag($form); ?>        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('email')); ?>
                        <?= $this->formElement($form->get('email')); ?>
                        <?= $this->formElementErrors($form->get('email')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('full_name')); ?>
                        <?= $this->formElement($form->get('full_name')); ?>
                        <?= $this->formElementErrors($form->get('full_name')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('status')); ?>
                        <?= $this->formElement($form->get('status')); ?>
                        <?= $this->formElementErrors($form->get('status')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('roles')); ?>
                        <?= $this->formElement($form->get('roles')); ?>
                        <?= $this->formElementErrors($form->get('roles')); ?>                  
                    </div>

                    <?= $this->formElement($form->get('csrf')); ?>
                    <?= $this->formElementErrors($form->get('csrf')); ?>
                    <?= $this->formElement($form->get('submit')); ?>        
                <?= $this->form()->closeTag(); ?>
            </div> <!-- panel-body -->
        </div> <!-- panel-primary (definition)  -->
    </div>   <! --column-md-6-- > 
</div>   

