<?php
    $this->headTitle('Users');

    $this->mainMenu()->setActiveItemId('users');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Users'=>$this->url('users'),
                ]);
?>

<!-- ******************************************* HTML RENDER ******************************************* -->

<div class="row">
    <div class="col-md-12">        
        <h3> MANAGE USERS </h3>            
        <div>
            <p> <!-- BUTTON NEW USER -->
                <a class="btn btn-default" href="<?= $this->url('users', ['action'=>'add']); ?>">
                    <span class="glyphicon glyphicon-plus ctp-green" aria-hidden="true"></span> New User
                </a>
            </p>
           <!-- TABLE: RENDERING USER'S DATA --> 
            <div class="table-responsive">
                <table class="minimalistBlack">
                    <!-- table header -->
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>E-mail</th>
                            <th>Full Name</th>
                            <th>Role(s)</th>        
                            <th>Date Created</th>
                            <th>Status</th>        
                            <th>Actions</th> 
                        </tr>
                    </thead>
                    <!-- table body -->
                    <tbody>
                        <?php foreach ($users as $user): ?>

                        <tr class="">
                            <td><?= $this->escapeHtml($user->getId()); ?></td>
                            <td>
                                <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                                    <?= $this->escapeHtml($user->getEmail()); ?>
                                </a> 
                            </td>
                            <td>
                                <?= $this->escapeHtml($user->getFullName()); ?></a> 
                            </td>
                            <td>
                                <?= $this->escapeHtml($user->getRolesAsString()); ?></a> 
                            </td>
                            <td><nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr></td>        
                            <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
                            <td>
                                <a id="ctp-borderDemo" class="btn btn-info btn-sm" href="<?= $this->url('users', 
                                        ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                                </a>
                                <span>&thinsp;</span>
                                <a id="ctp-borderDemo" class="btn btn-warning btn-sm" href="<?= $this->url('users',
                                        ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                                    <span class="glyphicon glyphicon-asterisk"></span> Change Password
                                </a>
                            </td>    
                        </tr>

                        <?php endforeach; ?>
                    </tbody>    
                </table>
            </div> <!-- table-responsive -->
        </div> <!-- panel-body -->      
    </div>  <!-- col-sm-12 -->
</div> <!-- row- bootstrap -->

<div class="row">
    <hr>
    <div class="col-md-2">
        <p> <!-- BUTTON NEW USER -->
            <span>&thinsp; </span>
            <a class="btn btn-default" href="<?= $this->url('users', ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus ctp-green" aria-hidden="true"></span> New User
            </a>
        </p>
    </div>
    
    <!-- BUTTONS PREVIOUS AND NEXT IMPLEMENTATION -->
    <div class="col-md-offset-7 col-md-3">
        <div class="btn-group">
            <a title="click to see Previous 15 Items" href="#">
                <button class="btn btn-default" type="button">
                    <span class="glyphicon glyphicon-menu-left ctp-green" aria-hidden="true"></span> Previous 
                </button>
            </a>    
            <a title="click to see Next 15 Items" href="#">
                <button class="btn btn-default" type="button">Next 
                    <span class="glyphicon glyphicon-menu-right ctp-green" aria-hidden="true"></span> 
                </button>
            </a>     
        </div>
    </div>
</div> <!-- END: BUTTONS ROW: NEW USER, PREVIOUS AND NEXT -->

<?php

//$this->paginationControl($users,
//                    'Sliding',
//                    'user/partial/paginator', 
//                    ['route' => 'users');
?>
