<?php
    $this->headTitle('Users');

    $this->mainMenu()->setActiveItemId('users');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Users'=>$this->url('users'),
                ]);
?>
   
<!-- ******************************************* HTML RENDER ******************************************* -->

<div class="row">
    <div class="col-md-12">        
        <h3> MANAGE USERS </h3>            
        <div>
            <p> <!-- BUTTON NEW USER -->
                <a class="btn btn-default" href="<?= $this->url('users', ['action'=>'add']); ?>">
                    <span class="glyphicon glyphicon-plus ctp-green" aria-hidden="true"></span> New User
                </a>
            </p>
           <!-- TABLE: RENDERING USER'S DATA --> 
            <div class="table-responsive">
                <table class="minimalistBlack">
                    <!-- table header -->
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th><span><i class= "fa fa-envelope"></i></span> E-mail</th>
                            <th><span><i class= "fa fa-user"></i></span> Full Name</th>
                            <th><span><i class= "fa fa-odnoklassniki"></i></span> Role(s)</th>        
                            <th><span><i class= "fa fa-table"></i></span> Date Created</th>
                            <th><span><i class= "fa fa-users"></i></span> Status</th>        
                            <th><span><i class= "fa fa-gear"></i></span> Actions</th> 
                        </tr>
                    </thead>
                    <!-- table body -->
                    <tbody>
                        <?php foreach ($users as $user): ?>
                        <tr>
                            <td><?= $this->escapeHtml($user->getId()); ?></td>
                            <td>
                                <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                                    <?= $this->escapeHtml($user->getEmail()); ?>
                                </a> 
                            </td>
                            <td>
                                <?= $this->escapeHtml($user->getFullName()); ?></a> 
                            </td>
                            <td>
                              <a href="#" data-toggle="modal" data-target="#basicModal">
                                Role List
                              </a>
                              
                               
                            </td>
                            <td><nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr></td>        
                            <td>
                                <?php
                                    $classRender = ($this->escapeHtml($user->getStatusAsString()=='Active'))? "ctp-green":"ctp-red";
                                ?>  
                                <!-- rendering USER's STATUS: green: means ACTIVE, red: means: INACTIVE -->
                                <span class=<?=$colorRender;?>> <i class="fa fa-circle "></i></span>                                
                            </td>
                            <td>
                                <a id="ctp-borderDemo" class="btn btn-info btn-sm" href="<?= $this->url('users', 
                                        ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                                </a>
                                <span>&thinsp;</span>
                                <a id="ctp-borderDemo" class="btn btn-warning btn-sm" href="<?= $this->url('users',
                                        ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                                    <span class="glyphicon glyphicon-asterisk"></span> Change Password
                                </a>
                            </td>    
                        </tr>

                        <?php endforeach; ?>
                    </tbody>    
                </table>
            </div> <!-- table-responsive -->
        </div> <!-- panel-body -->      
    </div>  <!-- col-sm-12 -->
</div> <!-- row- bootstrap -->

<div class="row">
    <hr>
    <div class="col-md-2">
        <p> <!-- BUTTON NEW USER -->
            <span>&thinsp; </span>
            <a class="btn btn-default" href="<?= $this->url('users', ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus ctp-green" aria-hidden="true"></span> New User
            </a>
        </p>
    </div>
    
    <!-- BUTTONS PREVIOUS AND NEXT IMPLEMENTATION -->
    <div class="col-md-offset-7 col-md-3">
        <div class="btn-group">
            <a title="click to see Previous 15 Items" href="#">
                <button class="btn btn-default" type="button">
                    <span class="glyphicon glyphicon-menu-left ctp-green" aria-hidden="true"></span> Previous 
                </button>
            </a>    
            <a title="click to see Next 15 Items" href="#">
                <button class="btn btn-default" type="button">Next 
                    <span class="glyphicon glyphicon-menu-right ctp-green" aria-hidden="true"></span> 
                </button>
            </a>     
        </div>
    </div>
</div> <!-- END: BUTTONS ROW: NEW USER, PREVIOUS AND NEXT -->

<!-- MODAL DIALOG BOX -->
<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">

          <h3  class="modal-title ctp-green" id="myModalLabel">Role List </h3>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">x</span>
          </button>
        </div>
        <div class="modal-body">
          <?=$this->escapeHtml($user->getRolesAsString())?>
        </div>
        <!--  
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

        </div>
        -->
      </div>
    </div>                                  
</div> 

<?php

//$this->paginationControl($users,
//                    'Sliding',
//                    'user/partial/paginator', 
//                    ['route' => 'users']);
//?>
