<?php
    $this->headTitle('Message');


 $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Password Reset'=>$this->url('users'),                
                ]);


 ?>
 <!--***************************************** RENDERING HTML ********************************************-->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5 single-service-item">
            <h4 class="title"> Message </h4>
                        
            <div class=" ">
                <?php if ($id=='sent'): ?>
                        <p> A password reset link has been sent to your email address.</p>
                <?php elseif ($id=='invalid-email'): ?>
                       <p> There is no user with such an email.</p>
                <?php elseif ($id=='set'): ?>
                       <p>Your new password has been <i>set</i> successfully. </p>
                        <p> 
                            Click <a class="base-color" href="<?= $this->url('login'); ?>">HERE </a> to login page.
                        </p>
                <?php elseif ($id=='failed'): ?>
                    Invalid reset key or it may have expired. Please return 
                    <a class="nav-link" href="<?= $this->url('reset-password') ?>">here</a> and try reset your password again.
                
                <?php endif; ?>
            </div>  
             <!-- P TAG: THERE ARE TWO BUTTONS -->
            <div class="btn-wrapper">
                <!-- BUTTON CHANGE PASSWORD -->
                <div class="btn-wrapper">
                            <a href="<?=$this->url('home'); ?>" class="boxed-btn">Go Back To Home</a>
                </div>    
            </div> 
            
         </div>         
    </div>
</div>   <!-- row will be render on the CONTAINER --> 