<?php
    $this->headTitle('Message');
?>

<!--***************************************** RENDERING HTML ********************************************-->
<div class="row">
    <div class="col-md-offset-4 col-md-5">
         <div class="panel panel-primary">
            <div class="panel-heading">
                <span class="zf-green">Reset Password </span>
            </div>            
            <div class="panel-body zdt-toolbar-info">
                <?php if ($id=='sent'): ?>
                        <p> A password reset link has been sent to your email address.</p>
                <?php elseif ($id=='invalid-email'): ?>
                       <p> There is no user with such an email.</p>
                <?php elseif ($id=='set'): ?>
                       <p>Your new password has been <i>set</i> successfully </p>
                        <p> 
                            to <a href="<?= $this->url('login'); ?>">login page</a>.
                        </p>
                <?php elseif ($id=='failed'): ?>
                    Invalid reset key or it may have expired. Please return 
                    <a href="<?= $this->url('reset-password') ?>">here</a> and try reset your password again.
                </p>
                <?php endif; ?>
            </div>    
         </div>         
    </div>
</div>   <!-- row will be render on the CONTAINER --> 