<?php
$this->headTitle('Reset Password');


$this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Reset Password'=>$this->url('users')
]);


$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email address'
    ]);

$form->get('captcha')->setAttributes([
    'class'=>'form-control', 
//    'placeholder'=>'Email address'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'submit-btn'
    ]);

$form->prepare();
?>

<!------------------------------------- RENDERING HTML  --------------------------------------->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 single-service-item">
            <?= $this->form()->openTag($form); ?>

            <h4 class="title">Reset Password</h4>

            <p>Enter your e-mail address below to reset your password</p>

            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                              

            <?= $this->formElement($form->get('captcha')); ?>
            <p class="hint">Enter the letters above as you see them.</p>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->formElement($form->get('csrf')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
