<?php
    $this->headTitle('Set New Password');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Set New Password'=>$this->url('users'),                
                ]);

    $form->get('new_password')->setAttributes(array(
        'class'=>'form-control', 
        'placeholder'=>'Type New Password'
        ));
    $form->get('confirm_new_password')->setAttributes(array(
        'class'=>'form-control', 
        'placeholder'=>'Confirm New Password'
        ));
    $form->get('submit')->setAttributes(['class'=>'submit-btn']);
    $form->prepare();
?>

<!--******************************************** RENDERING HTML ************************************************-->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 single-service-item">
            <h4 class="title"> Set New Password </h4>
            
            <p>Enter your new password in the form below</p>
            
            <?= $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?= $this->formLabel($form->get('new_password')); ?>
                    <?= $this->formElement($form->get('new_password')); ?>
                    <?= $this->formElementErrors($form->get('new_password')); ?>                              
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('confirm_new_password')); ?>
                    <?= $this->formElement($form->get('confirm_new_password')); ?>
                    <?= $this->formElementErrors($form->get('confirm_new_password')); ?>   
                </div>    

                <?= $this->formElement($form->get('submit')); ?>

                <?= $this->formElement($form->get('csrf')); ?>

            <?= $this->form()->closeTag(); ?>
            
       </div>
    </div>
</div>
