<?php
    $this->headTitle('View User');

    $this->mainMenu()->setActiveItemId('users');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Users'=>$this->url('users'),
                'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
                ]);
?>

<!-- **************************************** FLASH MESSENGER RENDER ***************************************************-->
 
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<div class="row">
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading"> <span class="zf-green">USER INFO</span></div>            
            <div class="panel-body">
                <!-- P TAG: THERE ARE TWO BUTTONS -->
                <p>
                    <!-- BUTTON EDIT -->    
                    <a class="btn btn-info" href="<?= $this->url('users', 
                            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Edit
                    </a>
                    <!-- BUTTON CHANGE PASSWORD -->
                    <a class="btn btn-warning" href="<?= $this->url('users',
                            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                        <span class="glyphicon glyphicon-asterisk"></span> Change Password
                    </a>    
                </p>
                <!-- TABLE RESPONSIVE -->
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tr class="success">
                            <th>ID:</th>
                            <td><?= $this->escapeHtml($user->getId()) ?></th>
                        </tr>
                        <tr class="">
                            <th>E-mail:</th>
                            <td><?= $this->escapeHtml($user->getEmail()) ?></th>
                        </tr>
                        <tr class="success">
                            <th>Full Name:</th>
                            <td><?= $this->escapeHtml($user->getFullName()) ?></th>
                        </tr>
                        <tr class="">
                            <th>Date Created:</th>
                            <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
                        </tr>
                        <tr class="success">
                            <th>Status:</th>
                            <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
                        </tr>
                        <tr class="">
                            <th>Roles:</th>
                            <td><?= $this->escapeHtml($user->getRolesAsString()) ?></th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>