<?php
    $this->headTitle('View User');

    $this->mainMenu()->setActiveItemId('users');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Users'=>$this->url('users'),
                'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
                ]);
?>

<!-- **************************************** FLASH MESSENGER RENDER ***************************************************-->
 
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<div class="container">        
    <div class="row justify-content-center">
        <div class="col-md-7 single-service-item">                 
            <h4 class="title"> USER INFO </h4> 
            <br>         
            <div class="panel-body">                   
                <!-- TABLE RESPONSIVE -->
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tr>
                            <th>ID:</th>
                            <td><?= $this->escapeHtml($user->getId()) ?></td>
                        </tr>
                        <tr>
                            <th>E-mail</th>
                            <td><?= $this->escapeHtml($user->getEmail()) ?></td>
                        </tr>
                        <tr>
                            <th>Full Name</th>
                            <td><?= $this->escapeHtml($user->getFullName()) ?></td>
                        </tr>
                        <tr>
                            <th>Date Created</th>
                            <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td><?= $this->escapeHtml($user->getStatusAsString()) ?></td>
                        </tr>
                        <tr >
                            <th>Roles</th>
                            <td><?= $this->escapeHtml($user->getRolesAsString()) ?> </td>
                        </tr>
                    </table>
                </div>

                <!-- P TAG: THERE ARE TWO BUTTONS -->
                <div class="row center-block">                       

                    <!-- BUTTON EDIT -->  
                    <div class="col-md-4">    
                        <a class="boxed-btn" href="<?= $this->url('users', 
                                ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                            <span class="fa fa-edit" ></span> Edit
                        </a>
                    </div>

                    <!-- BUTTON CHANGE PASSWORD -->
                    <div class="col-md-4">
                        <a class="boxed-btn" href="<?= $this->url('users',
                                ['action'=>'change-psw', 'id'=>$user->getId()]); ?>">
                            <span class="fa fa-lock"></span> Change Password
                        </a> 
                    </div>

                </div>
            </div>            
        </div>
    </div>
</div>