<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('CTPSYSTEM')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

               
        <?php $PathLogo = $this->basePath().'/img/logo.png'; ?>
        
        <!-- Default  -->
        <?= $this->headLink([
                      'rel' => 'shortcut icon', 
                      'type' => 'image/vnd.microsoft.icon', 
                      'href' => $PathLogo ])       
         
             ->prependStylesheet($this->basePath('assets/css/style.css'))             
             ->prependStylesheet($this->basePath('assets/css/bootstrap.min.css')) 
             ->prependStylesheet($this->basePath('assets/css/fontawesome.all.css')) 
             ->prependStylesheet($this->basePath('assets/css/flaticon.css'))
             ->prependStylesheet($this->basePath('assets/css/animate.css'))
             ->prependStylesheet($this->basePath('assets/css/owl.carousel.min.css'))
             ->prependStylesheet($this->basePath('assets/css/magnific-popup.css'))               
             ->prependStylesheet($this->basePath('assets/css/responsive.css'))
     
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>
     
        
        <!-- Scripts -->
        <?= $this->headScript()                
            ->prependFile($this->basePath('ctpJS/ctp_functionsJS.js'))  
        
            ->prependFile($this->basePath('assets/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/js/popper.min.js'))        
            ->prependFile($this->basePath('assets/js/jquery.magnific-popup.js'))
            ->prependFile($this->basePath('assets/js/contact.js'))
            ->prependFile($this->basePath('assets/js/wow.min.js'))
            ->prependFile($this->basePath('assets/js/waypoints.min.js'))
           ->prependFile($this->basePath('assets/js/imagesloaded.pkgd.min.js'))
            ->prependFile($this->basePath('assets/js/isotope.pkgd.min.js'))
            ->prependFile($this->basePath('assets/js/jquery.counterup.min.js'))
            ->prependFile($this->basePath('assets/js/main.js')) 
            ->prependFile($this->basePath('assets/js/jquery.js'))  
               
        ?>
       
       <!-- including all scripts for using DATATABLES -->               
       <?php
            echo $this->partial('application/particialview/scripts-datatable',['pathLogo'=>$PathLogo]);
            
            //getting variables sent from a controller to layout            
            $buttons = $this->buttons ?? null;  
            $form = $this->form ?? null;            
        ?>
       
       <script src="https://use.fontawesome.com/cca3ab2cb4.js"></script>
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
    </head>
    
     <!-- PAGE BODY: MAIN LAYOUT  -->    
    <body>       
              
        <!--using particial view-->
        <?php
           echo $this->partial('application/particialview/preloader',['pathLogo'=>$PathLogo]);
        ?>   
        
    <!-- ************************************** PAGE HEADER BANNER *************************************-->        
    <nav class="navbar navbar-area navbar-expand-lg ">
        <div class="container">
            <a class="navbar-brand logo" href="<?= $this->url('home')?>">
                <img height="80" src="<?= $PathLogo;?>" alt="logo">
            </a>
            <div class="navbar-collapse collapse" id="apptidy">
                <!-- Navigation bar generated dynamically -->
                <?php
                    // Check if the activeMenuItemId passed to layout view model
                    // and if so, use it for setting active navbar item.
                    if (isset( $activeMenuItemId )) {
                        $this->mainMenu()->setActiveItemId( $activeMenuItemId );
                    }
                    // Render the navbar
                    echo $this->mainMenu()->render();
                ?>
            </div>
            <!-- /.navbar btn wrapper -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#apptidy" aria-controls="apptidy" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- navbar collapse end -->
        </div>
    </nav>
        
   <!-- breadcrumb area start -->
    <section class="breadcrumb-area breadcrumb-bg">
        <div class="">
            <div class="row">
               <div class="col-md-offset-4 col-md-8">
                    <div class="breadcrumb-inner">
                        <?= $this->pageBreadcrumbs()->render(); ?>                        
                    </div>                  
               </div>
                
                <!-- rendering buttons on the breadcrums passed by a controller -->
                <div class="col-md-4">
                    <div class="row">
                    <?php if (isset($buttons)): ?>                       
                        <?php foreach ( $buttons as $button ):?>
                            <div class ="col-md-3">
                                    <a title="<?=$button['title']?>" class="<?=$button['class']?>" href="<?= $this->url($button['url']['route'], $button['url']['action']); ?>">
                                        <i class="<?=$button['font-icon']?>" aria-hidden="true"></i> <?=$button['label']?>
                                    </a>                         
                            </div>
                        <?php endforeach; ?> 
                        
                        <!--rendering update button -->
                        <?php if (isset($form)): ?> 
                            <div class ="col-md-3">
                                <?php
                                    $form->get('submit')->setAttributes(['class'=>'boxed-btn-layout btn-rounded']);
  
                                    /* prepare for before rendering */
                                    $form->prepare(); 
                                ?>
                                <?= $this->form()->openTag($form); ?> 
                                    <?= $this->formElement($form->get('csrf')); ?>                                        
                                    <?= $this->formElement($form->get('submit')); ?>
                            </div>
                        <?php endif; ?> 
                     <?php endif; ?>                      
                    </div>
                </div> 
            </div>
        </div>
    </section>
    <!-- breadcrumb area end -->   
    
    <!-- CONTENT TO BE RENDER -->
    <section class="ctp-container">
        <div class="container-fluid">       
            <div class="row">   
                <div class="col-lg-12">                    
                    <!-- Page content placeholder -->                    
                    <?= $this->content; ?>                     
                </div>
            </div>
        </div>
    </section>  
   
       
  <!-- back to top area start -->
  <div class="back-to-top">
        <i class="fas fa-angle-up"></i>
  </div>
    <?= $this->inlineScript() ?>     
    </body>
</html>
