<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('CTP SYSTEM')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('description', '')
            ->appendName('author', '')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/signin.css'))  //added by kristov magov
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))        
            ->prependFile($this->basePath('js/holder.min.js'))
            ->prependFile($this->basePath('js/ie10-viewport-bug-workaround.js'))
        ?>        
       </head>
  <body>        
      <div class="container">
          <div class="row bg-primary"> 
                <div class ="col-md-2">
                </div>    
                <div class="col-md-1 "> 
                    <img src="<?= $this->basePath('img/LOGO.PNG') ?>" height="60" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;
                </div>
                <div class="col-md-8">                                               
                    <h1 class="zf-green"> Welcome to CTP Information System</h1>                    
                </div>                
          </div>
          <div class = "row">
                <div class ="col-md-2">
                </div>    
                <div class="col-md-4"> 
                <p class = "costex-warning">
                     Costex Tractor Parts<br>
                     6100 N.W. 77th Ct<br>
                     Miami, FL 33166 <br>
                     Phone : (305)592-9769<br>
                     FAX   : (305)592-7355<br>
                </p> 
              </div>
          </div>
           <?= $this->content ?>
      </div>
      <div class="container  bg-primary">
           <hr>
          <div class = "col-md-offset-4 col-lg-8">             
              <a href='http://internalweb.costex.com/user-tools.php?page=directory'>CTP Phone System Directory</a>              
              <p ><font size="1" face="Verdana, Arial, Helvetica, sans-serif">© 2009 Costex Corporation, All Rights Reserved.</font>
              </p>
          </div>    
      </div>
  </body>
</html>
