<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('CTPSYSTEM')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                      'rel' => 'shortcut icon', 
                      'type' => 'image/vnd.microsoft.icon', 
                      'href' => $this->basePath().'/img/logo.png']
                  )->prependStylesheet($this->basePath('css/style.css'))
                   ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                   ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                   ->prependStylesheet($this->basePath('css/stylelayout.css'))
        ?>
        
         <!-------------------------------------------------------------------------------------------- 
           Link remote defined by Kristofer. 
           - All the icons in the icon libraries below, are scalable vector icons that can be customized with
             CSS (size, color, shadow, etc.)
        
        
        -------------------------------------------------------------------------------------------------->
        <?= $this->headLink([
                      'rel' => 'stylesheet',                        
                      'href' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css']
                  );
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
        
        <?php
             //----- getting PATH for banner.png inside the document root ---------------
             $bannerPath = $this->basePath().'/img/banner.png'; 
        ?>
        
        
    </head>
    
    <body style = "margin-top: 20px;">
        <!-- Page header -->
        <div class="header container-fluid">
                <div class=" ">
                    <div class="row">                    
                        <div>    
                            <a href="<?= $this->url('home')?>">
                                <img src="<?= $this->basePath().'/img/LOGO.PNG' ?>" height="80" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>
                            </a>
                        </div>    

                        <div class="">
                            <em> Information System</em>
                        </div>
                    </div>
                </div> 
            </div> 
        
        <!-- Page Content from here -->
        <div class="container">             
            <div class="row top-buffer">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?= $this->content; ?>
                </div>
            </div>
        </div> 
        
        <hr>
         <div class="container-fluid  jumbotron text">              
        <footer class="container text text-nowrap text-center">
            <p> Costex Tractor Parts. All rights reserved.</p>
        </footer>
    </div> 
    
        <?= $this->inlineScript() ?>
    </body>
</html>
