<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('CTPSYSTEM')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- default -->
    <?= $this->headLink([
                  'rel' => 'shortcut icon', 
                  'type' => 'image/vnd.microsoft.icon', 
                  'href' => $this->basePath().'/img/logo.png']) 
               //added from the new template   
               ->prependStylesheet($this->basePath('assets/css/style.css'))
               ->prependStylesheet($this->basePath('assets/css/bootstrap.min.css')) 
               ->prependStylesheet($this->basePath('assets/css/fontawesome.all.css')) 
               ->prependStylesheet($this->basePath('assets/css/flaticon.css'))
               ->prependStylesheet($this->basePath('assets/css/animate.css'))
               ->prependStylesheet($this->basePath('assets/css/owl.carousel.min.css'))
               ->prependStylesheet($this->basePath('assets/css/magnific-popup.css'))               
               ->prependStylesheet($this->basePath('assets/css/responsive.css'))

    ?>

    <!-- Scripts -->
    <?= $this->headScript()       
        ->prependFile($this->basePath('assets/js/bootstrap.min.js'))        
        ->prependFile($this->basePath('assets/js/popper.min.js'))        
        ->prependFile($this->basePath('assets/js/owl.carousel.min.js'))
        ->prependFile($this->basePath('assets/js/jquery.magnific-popup.js'))
        ->prependFile($this->basePath('assets/js/contact.js'))
        ->prependFile($this->basePath('assets/js/wow.min.js'))
        ->prependFile($this->basePath('assets/js/waypoints.min.js'))
        ->prependFile($this->basePath('assets/js/imagesloaded.pkgd.min.js'))
        ->prependFile($this->basePath('assets/js/isotope.pkgd.min.js'))    
        ->prependFile($this->basePath('assets/js/main.js')) 
        ->prependFile($this->basePath('assets/js/jquery.js'))    
    ?>

    <?php $bannerPath = $this->basePath().'/assets/img/logo.png'; ?>
        
</head>

<!--LOGGIN BODY--> 
    <body>        
    <!-- RENDERING PRELOADER USING PARTIAL VIEW -->
    <?php
       echo $this->partial('application/particialview/preloader',['pathLogo'=>$this->basePath().'/img/LOGO.PNG']);
    ?>    
    <!-- Page Content from here -->
    <div class="">
    <div class="container">             
        <div class="row">   
            <div class="col-lg-12">
                <div class="col-md-4 offset-md-8 text-center">            
                    <?= $this->content;?>
                </div>     
            </div>
        </div> 
    </div> 
    </div>   


    <?= $this->inlineScript() ?>
</body>
</html>
