<?php
    /*getting values */
       
    $this->headTitle('Watch');	
    $this->mainMenu()->setActiveItemId('claims'); 
   
    $this->pageBreadcrumbs()->setItems([
        'Home'=>$this->url('home'),
        'Watch Documents'=>$this->url('watch')       
        ]);       
   
    $user = $this->user;
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<div class="container">           
   <div class = "row panel">
       
   </div>
   
</div>       
