<?php
    $this->headTitle('View Project');

    $this->mainMenu()->setActiveItemId('productdev');

    // variables sent by the ViewModel   
    /**
     * @var Purchasing\Entity\Project
     */
    $projectObj = $this->projectObj;
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Projects'=>$this->url('productdev'),
                'View Project'=>$this->url('productdev', ['action'=>'view', 'id'=>$projectObj->getCode()])
                ]);
?>

<!-- **************************************** FLASH MESSENGER RENDER ***************************************************-->
 
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<div class="container">        
    <div class="row justify-content-center">
        <div class="col-md-8 single-service-item">                 
            <h4 class="title"> PROJECT INFO </h4> 
            <br>         
            <div class="panel-body">                   
                <!-- TABLE RESPONSIVE -->
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tr>
                            <th>Project Code:</th>
                            <td><?= $this->escapeHtml($projectObj->getCode() ) ?></td>
                        </tr>
                        <tr>
                            <th>Project Name</th>
                            <td><?= $this->escapeHtml($projectObj->getName()) ?></td>
                        </tr>
                        <tr>
                            <th>Project Description</th>
                            <td><?= $this->escapeHtml($projectObj->getDescription()) ?></td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td><?= $this->escapeHtml($projectObj->getStatusAsString()) ?></td>
                        </tr>
                        <tr>
                            <th>Creation User:</th>
                            <td><?= $this->escapeHtml($projectObj->getCreationUser()) ?></td>
                        </tr>                        
                    </table>
                </div>

                <!--THERE ARE TWO BUTTONS--> 
                <div class="row center-block"> 
                     <!--BUTTON EDIT-->   
                    <div class="col-md-4">    
                        <a class="boxed-btn" href="
                           <?= 
                              $this->url('productdev', ['action'=>'edit', 'id'=> $projectObj->getCode()]); 
                           ?>">
                            <span class="fa fa-edit" ></span> Edit
                        </a>
                    </div>

                     <!--GO TO WISH LIST--> 
                    <div class="col-md-4">
                        <a class="boxed-btn" href="<?= $this->url('wishlist', ['action'=>'index']);?>">
                            <span class="fa fa-backward"></span> Return WL
                        </a> 
                    </div>

                </div>
            </div>            
        </div>
    </div>
</div>