<?php
    $this->headTitle('Add Role');

    $this->mainMenu()->setActiveItemId('roles');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Roles'=>$this->url('roles'),
                'Add Role'=>$this->url('roles', ['action'=>'add'])
                ]);

    $form->get('name')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter name'
        ]);

    $form->get('description')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter description'
        ]);

    $form->get('inherit_roles')->setAttributes([
        'class'=>'form-control', 
        ]);

    $form->get('submit')->setAttributes(['class'=>'submit-btn']);

    $form->prepare();
?>

<div class="content ">
    <div class="row justify-content-center">
    <!-- RENDERING FORM ELEMENTS -->
   
        <!--LEFT COLUMN-->
        <div class="col-md-4 single-service-item ctp-magins">           
            <h4> NEW ROLE </h4> 
            <p> Please fill out the following form and click the <i>Create</i> button </p>
            
            <div class="form-group">                
                <?= $this->form()->openTag($form); ?>
                <i class="fa fa-universal-access"></i>
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>                  
            </div>
            
            <div class="form-group">
                <i class="fa fa-prescription-bottle"></i>
                <?= $this->formLabel($form->get('description')); ?>
                <?= $this->formElement($form->get('description')); ?>
                <?= $this->formElementErrors($form->get('description')); ?>  
                <br>
            </div>
            
            <div class="row">
                <div class="col-md-offset-4 col-md-8">  
                    <?= $this->formElement($form->get('csrf')); ?>
                    <?= $this->formElement($form->get('submit')); ?> 
                </div>
            </div>  
        </div>

        <!--RIGHT  COLUMN-->
        <div class="row single-service-item ctp-magins">                
            <div class="col-md-12 ">
                <?= $this->formLabel($form->get('inherit_roles')); ?>
                <?= $this->formElement($form->get('inherit_roles')); ?>
                <?= $this->formElementErrors($form->get('inherit_roles')); ?>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>  
    </div>
</div>




