<?php
    $this->headTitle('Edit Role');
    
    $this->mainMenu()->setActiveItemId('roles');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Roles'=>$this->url('roles'),               
                'Edit Role ' => $this->url('roles', ['action'=>'edit', 'id'=>$role->getId()])
                ]);
    
    
    //getting value from ViewModel()
    $form = $this->form;
    
    $form->get('name')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter name'
        ]);
    
    $form->get('description')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter description'
        ]);
    
    $form->get('inherit_roles')->setAttributes([
        'class'=>'form-control', 
        
        ]);
    
    
    $form->get('submit')
            ->setAttributes(['class'=>'submit-btn'])
            ->setValue(' Save ');
    
    $form->prepare();
?>

<div class="row justify-content-center">
    <div class="col-md-4 single-service-item"> 
        <h4>EDIT ROLE</h4>
        
        <div class="col-md-12">
            
            <!-- OPENNING FORM TAG -->
            <?= $this->form()->openTag($form); ?>        
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name')); ?>                  
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('description')); ?>
                    <?= $this->formElement($form->get('description')); ?>
                    <?= $this->formElementErrors($form->get('description')); ?>                  
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('inherit_roles')); ?>
                    <?= $this->formElement($form->get('inherit_roles')); ?>
                    <?= $this->formElementErrors($form->get('inherit_roles')); ?>
                </div>

                <?= $this->formElement($form->get('csrf')); ?>
            <div class="row"> 
               <div class="col-md-4">                         
                <?= $this->formElement($form->get('submit')); ?>        
               </div>
                &nbsp;
               <div class="col-md-offset-2 col-md-4">
                    <a 
                       title="Edit permissions associated"
                        class="boxed-btn" 
                        href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
                      <i class="fa fa-edit"></i> Edit
                    </a>
                </div> 
            </div>
            <?= $this->form()->closeTag(); ?>
            <!-- BUTTON EDIT PERMISSIONS -->
                
            
            
        </div> <!-- END: DIV col-md-12 -->
        
    </div> <!-- DIV CONTAINER -->    
</div>   

