<?php
    //TEXT that will be shown in the TAB Title
    $this->headTitle('Edit Role Permissions');
    
    //setting roles as active Menu
    $this->mainMenu()->setActiveItemId('roles');
    
    //redering de Breadcrumbs on the page
    $this->pageBreadcrumbs()->setItems([
                 'Home'=>$this->url('home'),
                'Manage Roles'=>$this->url('roles'),               
                'Edit Role ' => $this->url('roles', ['action'=>'edit', 'id'=>$role->getId()]),
                'Edit Permissions ' => $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]),
                ]);
    
    //getting BUTTON SUBMIT of the ViewModel sent in the $form variable 
    $form->get('submit')
            ->setAttributes(['class'=>'submit-btn'])
            ->setValue('  Save  ');
    
    //it's completly necessary before rendering each FORM        
    $form->prepare();
?>

<script language="JavaScript">          
 
    $(document).ready( function() {

        const buttons = {'excel':false, 'pdf':false, 'copy' : false};
        const dropDownsInCols = [];
        const initialConfig = dataTableConfig( dropDownsInCols, buttons ); 
        
        const table = renderDataTable(buttons, dropDownsInCols);
    }); 

</script>

<!-- TEXT that will be shown in the TAB Title -->

<div class="row justify-content-center">
    <div class="col-md-6 single-service-item">    	
        <h4> PERMISSIONS ASSIGNED TO ROLE: <span class="ctp-span">
        <em><?= $this->escapeHtml($role->getName()) ?></em></span></h4>
        <br>		    	
        <!-- OPENNING FORM TAG -->
        <?=$this->form()->openTag($form);?>
            <table class="table_ctp table_filtered display">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($allPermissions as $permission):
                        $disable = false;
                        $element = $form->get('permissions')->get($permission->getName());
                    ?>
                    <tr>
                        <td>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>" 
                                              value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                              <?php if ($element->isChecked()) {
                                                  echo 'checked';  
                                                  $disable = true; 
                                                  $classText ='ctp-blue';
                                              }?>
                                              <?php if ($element->getAttribute('disabled')){
                                                  echo 'disabled'; 
                                                  $disable= true; 
                                                  $classText ='ctp-red'; 
                                              }?>
                                         > <!-- CLOSING INPUT CHECKBOX TAG -->
                                    <?php 
                                       if ($disable) {echo "<em class=$classText>";}
                                       echo $this->escapeHtml($element->getLabel()); 
                                       if ($disable) {echo "</em>";}
                                    ?>
                                </label>
                                <?= $this->formElementErrors($element); ?>                  
                            </div>
                        </td>
                        <td>
                            <?= $this->escapeHtml($permission->getDescription()) ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </tfoot>
            </table>
            <?= $this->formElement($form->get('csrf')); ?>            
            <?= $this->formElement($form->get('submit')); ?>        
        <?= $this->form()->closeTag(); ?>      
    </div>
</div>

<div class="row">
    <div class="col-md-6"> 
        
    </div>    
</div>   

