<?php
    //TEXT that will be shown in the TAB Title
    $this->headTitle('Roles');
    
    $this->mainMenu()->setActiveItemId('roles');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Roles'=>$this->url('roles'),
                ]);
?>

<script language="JavaScript">          
 
    $(document).ready( function() {

        const buttons = {'excel':false, 'pdf':false, 'copy' : false};
        const dropDownsInCols = [];
        const initialConfig = dataTableConfig( dropDownsInCols, buttons ); 
        
        const table = renderDataTable(buttons, dropDownsInCols);
    }); 

</script>

<!------------------------------------------------------------------------------------------------------------------------------------>
<!-- ROW #1: DEFINING HEADER AND BUTTON SPACING -->

<div class="container">   

    <!--  FLASH MESSENGER WILL BE RENDERED WITH THE MESSAGE GENERADED -->
    <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
    <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
    <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

    <table class="table_ctp table_filtered display">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date Created</th>
                <th>Actions</th>        
            </tr>
        </thead>  
        <tbody>
            <!-- GENERATING EACH ROW WITH ROLES INFORMATION -->
            <?php foreach ($roles as $role): ?>
                <tr>
                    <td><?= $this->escapeHtml($role->getId()); ?></td>
                    <td class="description">
                        <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                            <?= $this->escapeHtml($role->getName()); ?>
                        </a> 
                    </td>
                    <td class="description"><?= $this->escapeHtml($role->getDescription()); ?>
                    </td>
                    <td><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>        
                    <td>
                        <nobr>
                            <a title="Edit" id="ctp-borderDemo" class="btn btn-info btn-sm" href="<?= $this->url('roles', 
                                    ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                                <span class="fa fa-edit fa-1x" ></span>
                            </a>
                            <a title="Delete"  id="ctp-borderDemo" class="btn btn-danger btn-sm" href="<?= $this->url('roles',
                                    ['action'=>'delete', 'id'=>$role->getId()]); ?>">
                                <span class="fa fa-eraser fa-1x"></span>
                            </a>
                        </nobr>
                    </td>    
                </tr>
            <?php endforeach; ?> 
        </tbody> 
        <tfoot>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date Created</th>
                <th>Actions</th>        
            </tr>
        </tfoot>
    </table>
</div>
 



