<?php
    //TEXT that will be shown in the TAB Title
    $this->headTitle('Roles');
    
    $this->mainMenu()->setActiveItemId('roles');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Roles'=>$this->url('roles'),
                ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<div class="row">
    <div class="col-md-12">
    	<div class="panel panel-success">
    		<div class="panel-heading">MANAGE ROLES</div>
    			<div class="panel-body">
                            <p>
                                <a class="btn btn-default" href="
                                    <?= $this->url('roles', ['action'=>'add']); ?>">
                                    <span class="glyphicon glyphicon-plus ctp-red" aria-hidden="true"></span> New Role
                                </a>
                            </p>
                    <table class="table table-striped">
                       <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Date Created</th>
                            <th>Actions</th>        
                        </tr>
                        
                        <?php foreach ($roles as $role): ?>
                        
                        <tr>
                            <td><?= $this->escapeHtml($role->getId()); ?></td>
                            <td>
                                <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                                    <?= $this->escapeHtml($role->getName()); ?>
                                </a> 
                            </td>
                            <td><?= $this->escapeHtml($role->getDescription()); ?></a> 
                            </td>
                            <td><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>        
                            <td>
                                </nobr>
                                <a class="btn btn-info" href="<?= $this->url('roles', 
                                        ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                                </a>
                                <a class="btn btn-danger" href="<?= $this->url('roles',
                                        ['action'=>'delete', 'id'=>$role->getId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span> Delete
                                </a>
                                </nobr>
                            </td>    
                        </tr>
                            
                        <?php endforeach; ?> 
                    </table>
                  </div> <!-- END: DIV panel-body -->
         </div> <!-- END: DIV panel-success -->
    </div> <!-- END: DIV col-md-12 : defining 6 columns on bootstramp -->    
</div> <!-- END: DIV BOOTSTRAP ROW -->   




