<?php
    //TEXT that will be shown in the TAB Title
    $this->headTitle('View Role');
    
    $this->mainMenu()->setActiveItemId('roles');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Roles'=>$this->url('roles'),
                'View Role ' => $this->url('roles', ['action'=>'view', 'id'=>$role->getId()])
                ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<!-- ROLE INFO PANEL -->    
<div class="row">
    <div class="col-md-8">
    	<div class="panel panel-success">
    		<div class="panel-heading">
    			ROLE: <span class="ctp-red"><?= $this->escapeHtml($role->getName()) ?> </span>
    		</div>
    		
			<div class="panel-body">
				<!-- EDIT ROLE BUTTON -->
				<p>
                    <a class="btn btn-default" href="<?= $this->url('roles', 
                                        ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil ctp-red" ></span> Edit Role
                    </a>
                </p>
                <table class="table table-striped table-bordered">
                     <tr>
                        <th>ID:</th>
                        <td><?= $this->escapeHtml($role->getId()) ?></th>
                    </tr>
                    <tr>
                        <th>Name:</th>
                        <td><?= $this->escapeHtml($role->getName()) ?></th>
                    </tr>
                    <tr>
                        <th>Description:</th>
                        <td><?= $this->escapeHtml($role->getDescription()) ?></th>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td><?= $this->escapeHtml($role->getDateCreated()) ?></th>
                    </tr>
                </table>
    		</div> <!-- END: DIV panel-body -->
         </div> <!-- END: DIV panel-success -->
    </div>
</div>

<!-- PERMISSIONS PANEL -->
<div class="row">
    <div class="col-md-8">
    	<div class="panel panel-success">
    		<div class="panel-heading">
    			EDIT PERMISSION 
    		</div>
    		
			<div class="panel-body">
				<!-- BUTTON EDIT PERMISSIONS -->
				<p>
                    <a class="btn btn-default" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
                      <span class="glyphicon glyphicon-check ctp-red"></span> Edit Permissions
                    </a>
            	</p>
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                    <?php foreach($allPermissions as $permission): ?>
                    <tr>
                        <td>
                            <input type="checkbox" disabled  <?php 
                            $colorText = 'ctp-black';
                            if (isset($effectivePermissions[$permission->getName()])) {echo 'checked'; $colorText = 'ctp-red';}?>>
                            <?php echo"<span class= $colorText>".$this->escapeHtml($permission->getName())."</span>";?>
                            <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                            <em class=<?=$colorText ?>>(inherited)</em>
                            <?php endif; ?>
                        </td>
                        <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
    	 	</div> <!-- END: DIV panel-body -->
         </div> <!-- END: DIV panel-success -->
    </div>
</div>
