<?php
    //TEXT that will be shown in the TAB Title
    $this->headTitle('View Role');
    
    $this->mainMenu()->setActiveItemId('roles');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Roles'=>$this->url('roles'),
                'Edit Permissions' => $this->url('roles', ['action'=>'view', 'id'=>$role->getId()])
                ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<script language="JavaScript">           
    $(document).ready( function() {

        const buttons = {'excel':false, 'pdf':false, 'copy' : false};
        const dropDownsInCols = [1];
        const initialConfig = dataTableConfig( dropDownsInCols, buttons ); 
        
        const table = renderDataTable(buttons, dropDownsInCols);
    }); 

</script>

<!-- PANEL RENDERING ROLE INFO  -->   
<div class="row  justify-content-center">  
    
    <div class="row single-service-item">
         <!--<div class="row">-->
        <div class="col-md-5">
            <!----------------------------------------------------- PERMISSIONS TABLE ------------------------------------------------>
            <!-- TABLE WITH ROLE INFO -->
            <table class="table table-striped table-bordered ">
                <tr>
                   <th>ID:</th>
                   <td><?= $this->escapeHtml($role->getId()) ?></td>
                </tr>

                <tr>
                    <th>Name:</th>
                    <td><b><?= $this->escapeHtml($role->getName()) ?></b></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td><?= $this->escapeHtml($role->getDescription()) ?></td>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td><?= $this->escapeHtml($role->getDateCreated()) ?></td>
                </tr>

            </table>
            
            <!-- EDIT ROLE BUTTON -->
            <p>
               <a title="Edit roles features like: name, description and inherited roles" 
                   class="boxed-btn" href="<?= $this->url('roles', ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                    <span class="fa fa-edit" ></span> Edit Role
               </a>
            </p>
                
        </div>
    
    
        <div class="col-md-6"> 
            <!-- RENDERING TABLE EDIT PERMISSIONS FOR A GIVEN ROLE --->
            <table class="table_ctp table_filtered display description">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php foreach($allPermissions as $permission): ?>
                        <tr>
                            <td>
                                <input type="checkbox" disabled  
                                    <?php 
                                        $colorText = 'ctp-black';
                                        if (isset($effectivePermissions[$permission->getName()])) 
                                            {echo 'checked'; $colorText = 'ctp-red';}
                                    ?>>
                                <?php echo"<span class= $colorText>".$this->escapeHtml($permission->getName())."</span>";?>
                                <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                                <em class=<?=$colorText ?>>(inherited)</em>
                                <?php endif; ?>
                            </td>
                            <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </tfoot>
            </table>    
            <br>
            <!-- BUTTON EDIT PERMISSIONS -->
            <p>
                <a title="Edit permissions associated to this role " class="boxed-btn" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
                  <span class="fa fa-edit"></span> Edit 
                </a>
            </p>
        </div>
    </div> <!-- END DIV: ROW WITH BUTTON EDIT PERMISSIONS -->
</div>
