<!--************************************************
    ADD.PHTML FILE
    - Let us Add a new Permission to the System 

****************************************************
-->

<?php
    $this->headTitle('Add Permission');

    $this->mainMenu()->setActiveItemId('permissions');

    $this->pageBreadcrumbs()->setItems([
        'Home'=>$this->url('home'),
        'Manage Permissions'=>$this->url('permissions'),
        'Add'=>$this->url('permissions', ['action'=>'add'])
    ]);

    $form->get('name')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter permission name'
        ]);

    $form->get('description')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter a description'
        ]);

    $form->get('submit')
            ->setAttributes(['class'=>'submit-btn'])
            ->setValue('  add  ');

    $form->prepare();
?>

 <div class="row justify-content-center">
    <div class="col-md-4 single-service-item">   	         
        <h4 class="title"> NEW PERMISSION </h4> 
        <p>
           Please fill out the following form and click the <i>Create</i> button.
        </p>    

           <?= $this->form()->openTag($form); ?>

               <div class="form-group">
                   <i class="fa fa-universal-access"></i>
                   <?= $this->formLabel($form->get('name')); ?>
                   <?= $this->formElement($form->get('name')); ?>
                   <?= $this->formElementErrors($form->get('name')); ?>                  
               </div>

               <div class="form-group">
                   <i class="fa fa-prescription-bottle"></i>
                   <?= $this->formLabel($form->get('description')); ?>
                   <?= $this->formElement($form->get('description')); ?>
                   <?= $this->formElementErrors($form->get('description')); ?>                  
               </div>

               <?= $this->formElement($form->get('csrf')); ?>

               <?= $this->formElement($form->get('submit')); ?>        
           <?= $this->form()->closeTag(); ?>
    </div>
</div>    




