<?php
    $this->headTitle('Edit Permission');
    
    $this->mainMenu()->setActiveItemId('permissions');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Permissions'=>$this->url('permissions'),
                'Edit Permission'=>$this->url('permissions', ['action'=>'edit', 'id'=>$permission->getId()])
                ]);
    
    $form = $this->form;
    
    $form->get('name')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter name'
        ]);
    
    $form->get('description')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter description'
        ]);
    
    $form->get('submit')
            ->setAttributes(['class'=>'ctp-btn'])
            ->setValue(' Save ');
    
    $form->prepare();
?>


<h2>EDIT PERMISSION <span class="ctp-span"><em><?= $this->permission->getName(); ?></em></span></h2> 

<div class="row">
    <div class="col-md-6">
    	<div class="ctp-container">           
    			
        <!-- OPEN FORM TAG -->
            <?= $this->form()->openTag($form); ?>        
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name')); ?>                  
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('description')); ?>
                    <?= $this->formElement($form->get('description')); ?>
                    <?= $this->formElementErrors($form->get('description')); ?>                  
                </div>

                <?= $this->formElement($form->get('csrf')); ?>
                <?= $this->formElement($form->get('submit')); ?>
            <!-- CLOSING FORM TAG -->
            <?= $this->form()->closeTag(); ?>
    </div> <!-- END: DIV col-md-6 : defining 6 columns on bootstramp -->    
</div> <!-- END: DIV BOOTSTRAP ROW -->   

