<?php
    $this->headTitle('Edit Permission');
    
    $this->mainMenu()->setActiveItemId('permissions');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Permissions'=>$this->url('permissions'),
                'Edit Permission'=>$this->url('permissions', ['action'=>'edit', 'id'=>$permission->getId()])
                ]);
    
    $form = $this->form;
    
    $form->get('name')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter name'
        ]);
    
    $form->get('description')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Enter description'
        ]);
    
    $form->get('submit')
            ->setAttributes(['class'=>'submit-btn'])
            ->setValue(' SAVE ');
    
    $form->prepare();
?>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 single-service-item">   	         
             <h4 class="title"> EDIT PERMISSION </h4> 
            <br>
            
        <!-- OPEN FORM TAG -->
            <?= $this->form()->openTag($form); ?>        
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name')); ?>                  
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('description')); ?>
                    <?= $this->formElement($form->get('description')); ?>
                    <?= $this->formElementErrors($form->get('description')); ?>                  
                </div>

                <?= $this->formElement($form->get('csrf')); ?>
                <?= $this->formElement($form->get('submit')); ?>
            <!-- CLOSING FORM TAG -->
            <?= $this->form()->closeTag(); ?>
        </div> <!-- END: DIV col-md-6 : defining 6 columns on bootstramp -->    
    </div> <!-- END: DIV BOOTSTRAP ROW -->   
</div>

