<?php
    $this->headTitle('Permissions');
    
    $this->mainMenu()->setActiveItemId('permissions');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Permissions'=>$this->url('permissions'),
                ]);
?>
<!--********************************  JAVASCRIPTS *************************************-->
<script language="JavaScript">          
 
    $(document).ready( function() {
        
        const buttons = {'excel':false, 'pdf':true, 'copy' : true};
        const dropDownsInCols = [];
        const initialConfig = dataTableConfig( dropDownsInCols, buttons ); 
        
        const table = renderDataTable(buttons, dropDownsInCols);
    }); 

</script>

<div class="container">  
  
    <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
    <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
    <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
  
  <table class="table_ctp table_filtered display">
    <thead>
        <tr>            
            <th>Name</th>
            <th>Description</th>
            <th>Date Created</th>
            <th><i class="fa fa-gears"></i> Actions</th>        
        </tr>
    </thead>

    
    <tbody>
        <?php foreach ($permissions as $permission): ?>

        <tr>           
            <td class="description">
                <a href="<?= $this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()]); ?>">
                    <?= $this->escapeHtml($permission->getName()); ?>
                </a> 
            </td>
            
            <td class="description"> <?= $this->escapeHtml($permission->getDescription()); ?></td>
            <td><?= $this->escapeHtml($permission->getDateCreated()); ?></td>
            
            <!-- COLUMN WITH EDIT AND DELETE BUTTONS -->
            <td>    
                
                <a class="btn btn-warning btn-sm" href="<?= $this->url('permissions', 
                        ['action'=>'edit', 'id'=>$permission->getId()]); ?>">
                    <i class="fa fa-edit" ></i>
                </a>
                &nbsp;
                <a class="btn btn-danger btn-sm" href="<?= $this->url('permissions',
                        ['action'=>'delete', 'id'=>$permission->getId()]); ?>">
                    <i class="fa fa-trash-alt"></i>
                </a>
                
            </td>    
        </tr>

        <?php endforeach; ?>   
    </tbody>
    <tfoot>
        <tr>             
          <th>Name</th>
          <th>Description</th>
          <th>Date Created</th>
          <th>Actions</th>        
        </tr>
    </tfoot>
  </table>

</div>


