<?php
    $this->headTitle('View Permission');
    
    $this->mainMenu()->setActiveItemId('permissions');
    
    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Manage Permissions'=>$this->url('permissions'),
                'View Permission'=>$this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()])
                ]);
?>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 single-service-item">
            <h4 class="title"> PERMISSION INFO </h4> 
            <br>
            <table class="table table-striped table-bordered">
                <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($permission->getId()) ?></th>
                </tr>
                <tr>
                    <th>Name:</th>
                    <td><?= $this->escapeHtml($permission->getName()) ?></th>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td><?= $this->escapeHtml($permission->getDescription()) ?></th>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td><?= $this->escapeHtml($permission->getDateCreated()) ?></th>
                </tr>
            </table>
            
             <!-- P TAG: THERE ARE TWO BUTTONS -->
            <div class="container row">
                <!-- BUTTON EDIT -->  
                <div class="col-md-4">    
                    <a class="boxed-btn" href="<?= $this->url('permissions', 
                            ['action'=>'edit', 'id'=>$permission->getId()]); ?>">
                        <span class="fa fa-edit" ></span> Edit
                    </a>
                </div>                                                
            </div>
        </div>
    </div>
</div>