<?php     
    /*getting values */
       
    $this->headTitle('Wish List');	
    $this->mainMenu()->setActiveItemId('Wish List'); 
   
    $this->pageBreadcrumbs()->setItems([
        'Home'=>$this->url('home'),
        'Wish List'=>$this->url('wishlist')       
        ]);       
    
    /*** getting params from IndexAction() inside LostsaleController ***/
   
    $table = $this->wishlist; 
    $form = $this->formNewItemWL;
    $renderAll = $this->renderAll;
    
    /* adding attributes to the form elements */
     $form->get('partnumber')->setAttributes([
        'class' => 'form-control',        
    ]);
    
        
    $form->get('submit')->setAttributes(['class'=>'submit-btn']);
  
    /* prepare for before rendering */
    $form->prepare();
    
 ?>  
 	 
<script language="JavaScript">          
    
    /*
     * JQuery code:
     * This occurs when the page has finished to load
    */    
    
    $(document).ready( function(){ 
        /* getting date() as String */
        
        const strDate = dateToStr();
        
        
//   taking off CLASS dt-button to the buttons EXCEL, PDF, AND COPY
    $("button.dt-button").removeClass("dt-button");
      
    //Initial Objet to config my table_filtered
    const initialConfig = {        

        "lengthMenu" :  [ [10, 25, 50, 100,  -1], 
                          [10, 25, 50, 100, "All"]
                        ],
                        
        dom: '<"ctp-buttons"l Bfr<t>ip>',
       
            /* see: exportOptions Object. This is an object. It help you to set up all concerning to BUTTONS */
            buttons: [ 
                    /* obj: BUTTON TO EXCEL */
                        { 
                            extend: 'excel', 
                            className: 'submit-btn', 
                            title: 'wishList-EXCEL-'+strDate+')', 
                            titleAttr : 'Convert to EXCEL',
                            text: 'E<u>X</u>CEL',                           
                            key: {
                                  key:'x',
                                  altKey: true
                                }
                        },
                        
                    /* OBJ: BUTTON to PDF */
                        {
                            extend: 'pdf',   
                            className: 'submit-btn', 
                            title: 'wishList-pdf-('+strDate+')',
                            titleAttr : 'Convert to PDF',
                            orientation: 'landscape',  //it's portrait by default 
                            pageSize: 'TABLOID', //this can be A3, A4, A5, LEGAL, LETTER or TABLOID  : all are STRINGS 
                            text: '<u>P</u>DF',                           
                            key: {
                                  key:'p',
                                  altKey: true
                                }
                            
                        }, //END: PDF BUTTON  OBJECT  
                                     
                        {
                            text        : 'IMPORT FROM EXCEL', 
                            className   : 'submit-btn'      
                        }                            
                                                                  
                     ],
        initComplete: function () {
            this.api().columns([1, 3,4,5,13,14,15,8,9]).every( function () { //[0,1, 8,10, 16, 18,19] : columns to apply 
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
                        column.search( val ? '^'+val+'$' : '', true, false ).draw();
                    } );

                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' );
                } );
            } );
        } //end property InitComplete                 
    };

    var tables = filterTable('table_filtered', initialConfig );
    
    //removing dt-button class to each HTMLElement (button) Associates to 
   // a table
    $('button').removeClass('dt-button');    
  
    }); 

</script>
        
<!-- HTML RENDER-->
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>    

<div class="container-fluid">
   <div class="row"> 
       <div class="col-md-auto">  
            <!--FILTER ACCORDION-->       
        <div class="accordion-wrapper contact-form-inner">
            <div id="accordion_2">               
                <div class="card">
                  <?=$this->form()->openTag($form);?> 
                    <div class="card-header" id="headingOne_2">
                        <h5 class="mb-0">
                            <a  class="collapsed" data-toggle="collapse" data-target="#collapseOne_2" aria-expanded="false" aria-controls="collapseOne_2">
                                <span class="">ADD ITEM(S)</span>
                            </a>
                        </h5>
                    </div>                  
                  <!--ACCORDION CONTENT--> 
                     <div id="collapseOne_2" class="collapse" aria-labelledby="headingOne_2" data-parent="#accordion_2">
                         <div class="card-body">
                             <div class = "row">                                      
                                    <?php 
                                       if ($renderAll) {
                                           echo '<div class="col-lg-6">'; 
                                             /*rendering code */
                                             echo $this->FormRow($form->get('code'))."<br>";   
                                             echo $this->FormRow($form->get('user'))."<br>";
                                             echo $this->FormRow($form->get('date'))."<br>";
                                             echo $this->FormRow($form->get('partnumber'));
                                             echo $this->FormRow($form->get('partnumberdesc'));
                                             echo "<br>";
                                         
                                       } else {
                                           echo '<div class="col-lg-8">'; 
                                           echo $this->FormRow($form->get('partnumber'));
                                       } 
                                       echo $this->formHidden($form->get('csrf')); 
                                       echo '<br>'.$this->FormElement($form->get('submit'));
                                       echo '</div>';
                                    ?> 
                                 

                                  <!-- second column -->
                                 <div class="col-lg-auto">
                                    <?php
                                       if ($renderAll) {
                                          echo $this->FormRow($form->get('vendor'));
                                          echo $this->FormRow($form->get('vendordesc'));
                                          echo "<br>";
                                          echo $this->FormRow($form->get('type'));

                                          echo "<br>";
                                          echo $this->FormRow($form->get('comment'));                                                                                     
                                       }
                                    ?>
                                 </div>
                             </div><!-- row defining body of ADD ITEM -->
                          </div> <!-- CARD-BODY --> 
                     </div>   <!-- COLLAPSE CONTENT END -->    
                    <?=$this->form()->closeTag();?>
                </div> <!-- CARD END -->            
            </div> <!-- ACCORDION END -->           
        </div>  <!-- ACCORDION WRAPPER -->         
    </div> <!-- COLUMN AUTO(INSIDE THIS IS THE ACCORDION --> 
   </div>
   
   </br>
   
   <!--rendering TABLE WISHLIST--> 
   <div class="row ">
       <div class="col-md-12">
          <?php echo $table; ?>
       </div> 
   </div>
</div>    
 