<?php     
    /*getting values */       
    $this->headTitle('NEW ITEM-WISHLIST');	
    $this->mainMenu()->setActiveItemId('Wish List'); 
   
    $this->pageBreadcrumbs()->setItems([
        'Home' => $this->url('home'),
        'Wish List' => $this->url('wishlist'),
        'Add' => $this->url('wishlist')       
        ]);       
    
    /*** getting params from IndexAction() inside LostsaleController ***/
  
    /**
    * @var Zend\Form  
    */  
    $form = $this->form;
    
    /**
     * @var boolean | Determining whether show all data from de part or not
     */
    
    $renderAll = $this->renderAll || false; 
        
    $columnStyle = $renderAll ? 'col-md-6 single-service-item ' : 'col-md-4 single-service-item'; 
     
    /* adding attributes to the form elements */
     $form->get('partnumber')->setAttributes([
        'class' => 'form-control',        
    ]);
    
        
    $form->get('submit')->setAttributes(['class'=>'submit-btn']);
  
    /* prepare for before rendering */
    $form->prepare();
    
 ?>  

<!--/********************************* CONTAINER TO BE RENDER ************************************************************/-->
<div class="container">        
    <div class="row justify-content-center">
        <div class="<?= $columnStyle; ?>">                 
            <h4 class="title"> NEW ITEM </h4> 
            <br>
            <!-- Open Form Tag -->
            <?= $this->form()->openTag($form); ?>
                <!-- EDIT: OLD PASSWORD -->
                <?php if ($renderAll ):?>
                    <div class="form-group"> 
                        <!--row 1-->
                        <div class="row">
                            <div class="col-md-2">
                                <?= $this->FormRow($form->get('code')); ?><br> 
                            </div>
                            <div class="col-md-4"> 
                                <?= $this->FormRow($form->get('user')); ?><br> 
                            </div>
                            <div class="col-md-6">                            
                                <?= $this->FormRow($form->get('date')); ?>                                 
                            </div>
                        </div>    
                        <!--row 2-->
                        <div class="row">
                            <div class="col-md-6">  
                                <?= $this->FormRow($form->get('partnumber')); ?><br>
                                <?= $this->FormRow( $form->get('vendor') ); ?>                              
                                <?= $this->FormRow($form->get('type')); ?> <br>                                
                            </div>
                            <div class="col-md-6">              
                                <?= $this->FormRow($form->get('partnumberdesc')); ?><br>
                                <?= $this->FormRow($form->get('vendordesc')); ?> 
                            </div>
                        </div>
                        <!--row 3-->
                        <div class="row">
                            <div class="col-md-12">                          
                                <?= $this->FormRow($form->get('comment')); ?>
                            </div>
                        </div>
                    </div>
                <?php else:?>
                    <?= $this->FormRow($form->get('partnumber')); ?>
                    <br>
                <?php endif;?>            
                <!-- CROSS SITE REQUEST FORGERY CHECKING -->    
                <?= $this->formElement($form->get('csrf')); ?>

                <div class="btn-wrapper">
                    <?= $this->formElement($form->get('submit')); ?>
                </div>
            <?= $this->form()->closeTag(); ?>
                       
        </div><!-- offset... -->
    </div>
</div>

 