<?php     
    /*getting values */
       
    $this->headTitle('NEW ITEM-WISHLIST');	
    $this->mainMenu()->setActiveItemId('Wish List'); 
   
    $this->pageBreadcrumbs()->setItems([
        'Home' => $this->url('home'),
        'Wish List' => $this->url('wishlist'),
        'Add' => $this->url('wishlist')       
        ]);       
    
    /*** getting params from IndexAction() inside LostsaleController ***/
  
    /**
    * @var Zend\Form  
    */  
    $form = $this->form;
    //determining whether show all data from de part or not
        
    /* adding attributes to the form elements */
     $form->get('partnumber')->setAttributes([
        'class' => 'form-control',        
    ]);
    
        
    $form->get('submit')->setAttributes(['class'=>'submit-btn']);
  
    /* prepare for before rendering */
    $form->prepare();    
 ?>  
         

<!--/********************************* CONTAINER TO BE RENDER ************************************************************/-->

<div class="container">        
    <div class="row justify-content-center">
        <div class="col-md-7 single-service-item">                 
            <h4 class="title"> NEW ITEM </h4> 
            <br>
            <!-- Open Form Tag  -->
            <?= $this->form()->openTag($form); ?>
                <!-- EDIT: OLD PASSWORD -->
                
                    <div class="form-group"> 
                        <!--row 1-->
                        <div class="row">
                          <div class="col-md-4">
                            <?= $this->FormRow($form->get('code')); ?>                              
                            <?= $this->FormRow($form->get('user')); ?>                            
                          </div>
                          <div class="col-md-4">                            
                             <?= $this->FormRow($form->get('partnumber')); ?>
                              <?= $this->FormRow($form->get('partnumberdesc')); ?>                           
                          </div>    
                          <div class="col-md-3">  
                              <?= $this->FormLabel($form->get('date')); ?>                            
                              <?= $this->FormElement($form->get('date')); ?>
                              
                              <?= $this->FormRow($form->get('price')); ?>
                              
                          </div>
                        </div>    
                        
                        <!--row 2-->
                        <div class ="row">
                          <div class="col-md-12">                                                       
                            <div class="row">    
                                <div class="col-md-4">                                    
                                    <?= $this->FormRow($form->get('model')); ?>
                                </div>    
                                <div class="col-md-2">
                                    <?= $this->FormRow($form->get('major')); ?>
                                </div>    
                                <div class="col-md-2">    
                                    <?= $this->FormLabel($form->get('minor')); ?><br>                                    
                                    <?= $this->FormElement($form->get('minor')); ?><br>                                    
                                </div>
                                <div class="col-md-3">
                                    <?= $this->FormLabel($form->get('type')); ?><br> 
                                    <?= $this->FormElement($form->get('type')); ?><br> 
                                </div>
                            </div> 
                          </div>      
                        </div>
                        <!--row 3-->
                        <div class="row">
                          <div class="col-md-10">
                            <br>  
                            <?= $this->FormRow($form->get('comment')); ?>
                          </div>
                        </div> 
                    </div>
                           
                <!-- CROSS SITE REQUEST FORGERY CHECKING -->    
                <?= $this->formElement($form->get('csrf')); ?>

                <div class="btn-wrapper">
                    <?= $this->formElement($form->get('submit')); ?>
                </div>
            <?= $this->form()->closeTag(); ?>
                       
        </div><!-- offset... -->
    </div>
</div>

 