<?php     
    /*getting values */
       
    $this->headTitle('Wish List');	
    $this->mainMenu()->setActiveItemId('Wish List'); 
   
    $this->pageBreadcrumbs()->setItems([
        'Home'=>$this->url('home'),
        'Wish List'=>$this->url('wishlist')       
        ]);       
    
    /*** getting params from IndexAction() inside LostsaleController ***/
   
    /**
     * @var Zend\Form Description
     */
    $form = $this->form;
    
    $table = $this->wldata;     
    $isPa = $this->isPa;
    $user = $this->user;    
    $urlInc = ( $this->urlInc ) ? $this->basePath().'/data/wishlist_inc.xls' : '';
    
    $form->get('submit')->setAttributes(['class'=>'submit-btn']);
  
    /* prepare for before rendering */
    $form->prepare();  
       
 ?>  
 	 
<script language="JavaScript">          
 
    $(document).ready( function() { 
         let isPa = "<?php echo $isPa; ?>";
         
         hideCols=[0];
         
         if (!isPa){
             hideCols =  [];
         }
         
    //   taking off CLASS dt-button to the buttons EXCEL, PDF, AND COPY
        $("button.dt-button").removeClass("dt-button");

        const buttons = {'excel':true, 'pdf':true, 'copy' : true};
        const dropDownsInCols = [ 1, 3, 4, 5, 7, 13, 18];
        const initialConfig = dataTableConfig( dropDownsInCols, buttons, hideCols);  

        var table = filterTable('table_filtered', initialConfig ); 
        
        //removing dt-button class to each HTMLElement (button) Associates to 
        // a datatable
        $('button').removeClass('dt-button');         
    }); 

</script>
        
<!-- HTML RENDER-->
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('error',   ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('info',    ['alert', 'alert-info']); ?>   

<?php if($urlInc !=''): ?>
    <div>
        <p> Click here to <a href="<?=$urlInc;?>" class="base-color">Download</a> inconcistencies!!!</p> 
    </div>
<?php endif;?>

<div class="container-fluid">
   <!--rendering actions-->  
   <?php if (!$isPa) :?>
            <!-- Open Form Tag  -->
        <?= $this->form()->openTag($form); ?> 
        <?= $this->partial('particialview/actions.phtml',['user'=>$user, 'form' => $form]);?> 
   <?php endif;?>
  
   </br>
   
   <!--rendering TABLE WISHLIST--> 
   <div class="row">
       <div class="col-md-12">
            <?php 
            
            if ($table !=='') {
                echo $table; 
            } else { ?>
                <div class="container  panel panel-info title">
                   <h3> "THE WISH LIST IS EMPTY OR THERE IS NO ITEM(s) ASSIGNED TO YOU" </h3>
                </div>
            <?php } ?>
       </div> 
   </div>
</div>    

<?= $this->partial('particialview/modal.phtml',['name'=>'User Name']);?> 

<?php if (!$isPa) :?>
     <?= $this->form()->closeTag(); ?>      
<?php endif;?>