<?php     
    /*getting values */
       
    $this->headTitle('Wish List');	
    $this->mainMenu()->setActiveItemId('Wish List'); 
   
    $this->pageBreadcrumbs()->setItems([
        'Home'=>$this->url('home'),
        'Wish List'=>$this->url('wishlist')       
        ]);       
    
    /*** getting params from IndexAction() inside LostsaleController ***/
   
    $table = $this->wldata; 
    $urlValid = $this->url1;
    

    if ( $urlValid) {
        $url1 = $this->basePath().'/data/wishlist_inc.xls';
    }
        
    /* adding attributes to the form elements */
//     $form->get('partnumber')->setAttributes([
//        'class' => 'form-control',        
//    ]);
    
        
//    $form->get('submit')->setAttributes(['class'=>'submit-btn']);
//  
//    /* prepare for before rendering */
//    $form->prepare();
    
 ?>  
 	 
<script language="JavaScript">          
 
    $(document).ready( function(){ 
    
//   taking off CLASS dt-button to the buttons EXCEL, PDF, AND COPY
    $("button.dt-button").removeClass("dt-button");
    
    const buttons = {'excel':true, 'pdf':true, 'copy' : true};
    const dropDownsInCols = [0, 1, 3, 4, 5, 13, 14, 15, 8, 9];
    const initialConfig = dataTableConfig( dropDownsInCols, buttons );  
    
    let tables = filterTable('table_filtered', initialConfig );    
    
    //removing dt-button class to each HTMLElement (button) Associates to 
    // a table
    $('button').removeClass('dt-button');    
  
    }); 

</script>
        
<!-- HTML RENDER-->
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>   

<?php if($url1!=''): ?>
    <div>
        <p> Click here to <a href="<?=$url1;?>" class="base-color">Download</a> inconcistencies!!!</p> 
    </div>
<?php endif;?>

<div class="container-fluid">
    <div class="row"> 
        <div class="col-md-auto">  
            <!--FILTER ACCORDION-->       
            <div class="accordion-wrapper contact-form-inner">
                <div id="accordion_2">               
                    <div class="card">

                        <div class="card-header" id="headingOne_2">
                            <h5 class="mb-0">
                                <a  class="collapsed" data-toggle="collapse" data-target="#collapseOne_2" aria-expanded="false" aria-controls="collapseOne_2">
                                    <span class="">ACTIONS</span>
                                </a>
                            </h5>
                        </div>                  
                      <!--ACCORDION CONTENT--> 
                        <div id="collapseOne_2" class="collapse" aria-labelledby="headingOne_2" data-parent="#accordion_2">
                            <div class="card-body">
                                <div class = "row">                                      
                                    <a class="boxed-btn" href="<?= $this->url('wishlist', ['action'=>'add']); ?>">
                                        <span class="glyphicon glyphicon-plus ctp-green" aria-hidden="true"></span> NEW ITEM
                                    </a>
                                    <a class="boxed-btn" href="<?= $this->url('wishlist', ['action'=>'add']); ?>">
                                        <span class="glyphicon glyphicon-plus ctp-green" aria-hidden="true"></span> UPDATE
                                    </a> 

<!--                                    <a class="boxed-btn" href="<1?= $this->url('wishlist', ['action'=>'add']); ?>">
                                        <span class="glyphicon glyphicon-plus ctp-green" aria-hidden="true"></span> DELETE
                                    </a>-->
                                    <a class="boxed-btn" href="<?= $this->url('wishlist', ['action'=>'upload']); ?>">
                                        <span class="glyphicon glyphicon-plus ctp-green" aria-hidden="true"></span> IMPORT FROM EXCEL
                                    </a>

                                </div>                           
                            </div> <!-- CARD-BODY --> 
                        </div>   <!-- COLLAPSE CONTENT END -->    

                    </div> <!-- CARD END -->            
                </div> <!-- ACCORDION END -->           
            </div>  <!-- ACCORDION WRAPPER -->         
    </div> <!-- COLUMN AUTO(INSIDE THIS IS THE ACCORDION --> 
   </div>
   
   </br>
   
   <!--rendering TABLE WISHLIST--> 
   <div class="row ">
       <div class="col-md-12">
          <?php 
           if ($table !=='') {
               echo $table; 
           } else {
               echo '<div class="panel">';
                  echo"wish list is empty";
               echo '</div">'   ;
           }    
          ?>
       </div> 
   </div>
</div>    

<?= $this->partial('particialview/modal.phtml',['name'=>'User Name']);?> 