<?php     
    /*getting values */
       
    $this->headTitle('UPDATE ITEMs');	
    $this->mainMenu()->setActiveItemId('Wish List'); 
   
    $this->pageBreadcrumbs()->setItems([
        'Home' => $this->url('home'),
        'Wish List' => $this->url('wishlist'),
        'Update' => $this->url('wishlist')       
        ]);       
    
    
    /*** getting params from IndexAction() inside LostsaleController ***/
  
    /**
    * @var Zend\Form  
    */  
    $form = $this->form;
    //determining whether show all data from de part or not
        
    /* adding attributes to the form elements */
    $form->get('partnumber')->setAttributes([
        'class' => 'form-control',        
    ]);
    $form->get('status')->setAttributes([
        'class' => 'form-control',        
    ]);
    
        
    $form->get('submit')->setAttributes(['class'=>'submit-btn']);
  
    /* prepare for before rendering */
    $form->prepare();    
 ?>  
         

<!--/********************************* CONTAINER TO BE RENDER ************************************************************/-->

<div class="container">        
    <div class="row justify-content-center">
        <div class="col-md-6 single-service-item">                 
            <h4 class="title"> UPDATE </h4> 
            <br>
            <!-- Open Form Tag  -->
            <?= $this->form()->openTag($form); ?>
                <!-- EDIT: OLD PASSWORD -->

                <div class=""> 
                    <!--row 1-->
                    <div class="row">
                      <div class="col-md-4">
                        <?= $this->FormRow($form->get('partnumber')); ?>                                                                                                                                 
                      </div>
                      <div class="col-md-8">                        
                        <?= $this->FormRow($form->get('status')); ?>                          
                      </div>
                    </div>   
                    <br>
                    <!--row 2-->
                    <div class="row">
                      <div class="col-md-12">                                                                            
                        <?= $this->FormRow($form->get('comment')); ?>                              
                      </div>
                    </div>    

                    <!-- CROSS SITE REQUEST FORGERY CHECKING -->    
                    <?= $this->formElement($form->get('csrf')); ?>
                    <br>
                    <div class="btn-wrapper">
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                </div><!-- offset... -->  
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

 