<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'About'=>$this->url('about'),
            ]);
?>

<h1>About Us</h1>
<div class="container">
    <div class="row">
        <div class="wpb_column vc_column_container col-sm-6">
            <div class="vc_column-inner vc_custom_1429174439045">
                <div class="wpb_wrapper">
                    <div id="section-6" class="dt-section-head left vc_custom_1452287963816 size-small" dir="ltr">
                        <div class="dt-section-container"><h2 class="section-main-title section-heading-thin-border thin-left" style="color:#ffffff;border-color:#ffd658">
                            Location Map
                        </h2>
                        </div>
                    </div>
                    <div class="wpb_text_column wpb_content_element ">
                        <div class="wpb_wrapper">
                                <p>
                                   <a href="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=6100+NW+77th+Ct,+Miami+FL+33166&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=62.443704,99.316406&amp;ie=UTF8&amp;hq=&amp;hnear=6100+NW+77th+Ct,+Miami,+Miami-Dade,+Florida+33166&amp;ll=25.829455,-80.322783&amp;spn=0.008585,0.012124&amp;t=h&amp;z=17&amp;iwloc=r0" target="_blank" rel="noopener noreferrer">
                                       <img class="alignnone wp-image-29818" src="img/map.jpg" alt="" width="344" height="406" scale="0">
                                   </a>
                                   <br>
                                </p>

                        </div> 
                    </div> 
                </div>
            </div>
        </div>
        <div class="wpb_column vc_column_container col-sm-4">
        <div class="vc_column-inner vc_custom_1429174448910">
            <div class="wpb_wrapper">
                        
                <div class="wpb_text_column wpb_content_element ">
                    <div class="wpb_wrapper">
                        <p>
                           <span style="color: #9f9f9f;">
                               At CTP, our focus is to provide you with great quality parts at a good value.
                               Our new replacement parts undergo strenuous and strict inspection procedures to
                               ensure the quality of our product. We are committed to a basic principle: 
                               Quality with Value Guaranteed. The product presentation is just as important 
                               as the product inside which comes with one of the best warranties in the industry. 
                               The CTP brand comes on each and every box, therefore you can be rest assured that 
                               our whole team is behind you every step of the way.
                           </span>
                        </p>
                        <h4 class="title2 elem9"><span style="color: #9f9f9;">Miami Headquarters:</span></h4>
                        <ul>
                        <li><span style="color: #9f9f9f;">
                                <i class="dt-icon icon-miu-house129"></i> 6100 N.W. 77th Court - Miami, Florida 33166 U.S.A.<br>
                        </span></li>
                        <li><span style="color: #9f9f9f;"><i class="dt-icon icon-miu-telephone96"></i> Tel: (305) 592-9769<br>
                        Toll Free in USA: 1 800 321 2451<br>
                        </span></li>
                        </ul>
                        <h4 class="title2 elem9"><span style="color: #9f9f9;">Dallas Branch:</span></h4>
                        <ul>
                            <li><span style="color: #9f9f9f;"><i class="dt-icon icon-miu-house129"></i> 1441 S. Beltline RD. Coppell, Texas 75019 Suite 100 U.S.A.</span><span style="color: #9f9f9f;"><br>
                            </span></li>
                            <li>
                                <span style="color: #9f9f9f;">
                                    <i class="dt-icon icon-miu-telephone96"></i> Tel: 1 214 231 7455<br>
                                </span>
                            <span style="color: #9f9f9f;">Toll Free in USA: 1 888 287 0580<br></span>
                            </li>
                        </ul>
                    </div> 
                </div> 
            </div>
        </div>
    </div>
        
        <div class="wpb_column vc_column_container vc_col-sm-2">
            <div class="vc_column-inner ">
                <div class="wpb_wrapper">
                    <div id="section-8" class="dt-section-head left vc_custom_1452286053134 size-small" dir="ltr">
                        <div class="dt-section-container"><h2 class="section-main-title section-heading-thin-border thin-left" style="color:#ffffff;border-color:#ffd658">
                            Social
                        </h2>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
