<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'About'=>$this->url('about'),            
            ]);
?>
<!-- about page content area start -->
<section class="about-page-conent about-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="left-content-area"><!-- left content area -->
                    <div class="tile-image-two"><!-- tile image two -->
                        <div class="img-one">
                            <img src="assets/img/tile-gallery/01.jpg" alt="tile images">
                        </div>
                        <div class="img-two">
                            <img src="assets/img/tile-gallery/02.jpg" alt="tile images">
                        </div>
                    </div><!-- //. tile image two -->
                </div>
            </div>
            <div class="col-lg-6">
                <div class="right-content-area"><!-- right coantne area -->
                    <h2 class="title">Why you choose us?</h2>
                    <p> At CTP, our focus is to provide you with great quality parts at a good value.
                               Our new replacement parts undergo strenuous and strict inspection procedures to
                               ensure the quality of our product. We are committed to a basic principle: 
                               Quality with Value Guaranteed. The product presentation is just as important 
                               as the product inside which comes with one of the best warranties in the industry. 
                               The CTP brand comes on each and every box, therefore you can be rest assured that 
                               our whole team is behind you every step of the way.</p>
                    
                    <div class="btn-wrapper">
                        <a href="#" class="boxed-btn">Contact us</a>
                    </div>
                </div><!-- right content area -->
            </div>
        </div>
    </div>
</section>
<!-- about page content area end-->

<!-- counter up area start -->
<section class="counterup-area counterup-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="single-counterup-item"><!-- single coutner up item -->
                    <div class="icon">
                        <i class="flaticon-briefcase"></i>
                    </div>
                    <div class="content">
                        <div class="count-num">3700</div>
                        <h5 class="name">Project Completed</h5>
                    </div>
                </div><!-- ///. single counter up item -->
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-counterup-item"><!-- single coutner up item -->
                    <div class="icon">
                        <i class="flaticon-face"></i>
                    </div>
                    <div class="content">
                        <div class="count-num">4048</div>
                        <h5 class="name">Happy Customer</h5>
                    </div>
                </div><!-- ///. single counter up item -->
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-counterup-item"><!-- single coutner up item -->
                    <div class="icon">
                        <i class="flaticon-team"></i>
                    </div>
                    <div class="content">
                        <div class="count-num">388</div>
                        <h5 class="name">Our Engnieer</h5>
                    </div>
                </div><!-- ///. single counter up item -->
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-counterup-item"><!-- single coutner up item -->
                    <div class="icon">
                        <i class="flaticon-team-1"></i>
                    </div>
                    <div class="content">
                        <div class="count-wrap"> <span class="count-num">3700</span>k+</div>
                        <h5 class="name">Follower</h5>
                    </div>
                </div><!-- ///. single counter up item -->
            </div>
        </div>
    </div>
</section>
<!-- counter up area end -->

<!-- team member area start -->
<div class="team-member-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="section-title"><!-- section title -->
                    <h2 class="title">Meet Our Experts</h2>
                    <div class="separator">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div><!-- //. section title -->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="single-team-member"><!-- single team member -->
                    <div class="thumb">
                        <img src="assets/img/team-member/01.jpg" alt="team image">
                    </div>
                    <div class="content">
                        <h4 class="name">Jose David</h4>
                        <span class="post">IT Director</span>
                        <p>
                            Tel: (305) 592-9769 (Ext:201) 
                            Fax: (305) 592-735
                            email: jdmercardo@costex.com
                        </p>   
                        <ul class="social-icon">
                            <li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-linkedin-in"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-google-plus-g"></i> </a></li>
                        </ul>
                    </div>
                </div><!-- //. single team member -->
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-team-member"><!-- single team member -->
                    <div class="thumb">
                        <img src="assets/img/team-member/02.jpg" alt="team image">
                    </div>
                    <div class="content">
                        <h4 class="name">Hugo Oliveros</h4>
                        <span class="post">Senior Analyst</span>
                        <p>
                            Tel: (305) 592-9769 (Ext:203) 
                            Fax: (305) 592-735
                            holiveros@costex.com
                        </p>   
                        <ul class="social-icon">
                            <li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-linkedin-in"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-google-plus-g"></i> </a></li>
                        </ul>
                    </div>
                </div><!-- //. single team member -->
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-team-member"><!-- single team member -->
                    <div class="thumb">
                        <img src="assets/img/team-member/03.jpg" alt="team image">
                    </div>
                    <div class="content">
                        <h4 class="name">Alejandro Alzate</h4>
                        <span class="post">Senior Development</span>
                         <p>
                            Tel: (305) 592-9769 (Ext:202) 
                            Fax: (305) 592-735
                            aalzate@costex.com
                        </p>    
                        <ul class="social-icon">
                            <li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-linkedin-in"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-google-plus-g"></i> </a></li>
                        </ul>
                    </div>
                </div><!-- //. single team member -->
            </div>           
        </div>
        <div class="row">
             <div class="col-lg-3 col-md-6">
                <div class="single-team-member"><!-- single team member -->
                    <div class="thumb">
                        <img src="assets/img/team-member/04.jpg" alt="team image">
                    </div>
                    <div class="content">
                        <h4 class="name">Juan David</h4>
                        <span class="post">Senior Analyst Dev</span>
                        <p>
                            Tel: (305) 592-9769 (Ext:204) 
                            Fax: (305) 592-735
                            jdmira@costex.com
                        </p>    
                        <ul class="social-icon">
                            <li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-linkedin-in"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-google-plus-g"></i> </a></li>
                        </ul>
                    </div>
                </div><!-- //. single team member -->
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-team-member"><!-- single team member -->
                    <div class="thumb">
                        <img src="assets/img/team-member/05.jpg" alt="team image">
                    </div>
                    <div class="content">
                        <h4 class="name">Blanca Otalora</h4>
                        <span class="post">IT Development Ass. </span>
                        <p>
                            Tel: (305) 592-9769 (Ext:230) 
                            Fax: (305) 592-735
                            botalora@costex.com
                        </p>    
                        <ul class="social-icon">
                            <li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-linkedin-in"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-google-plus-g"></i> </a></li>
                        </ul>
                    </div>
                </div><!-- //. single team member -->
            </div>
             <div class="col-lg-3 col-md-6">
                <div class="single-team-member"><!-- single team member -->
                    <div class="thumb">
                        <img src="assets/img/team-member/06.jpg" alt="team image">
                    </div>
                    <div class="content">
                        <h4 class="name">Michel Ojeda</h4>
                        <span class="post">Analyst Development</span>
                        <p>
                            Tel: (305) 592-9769 (Ext:230) 
                            Fax: (305) 592-735
                            mojeda@costex.com
                        </p>    
                        <ul class="social-icon">
                            <li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-linkedin-in"></i> </a></li>
                            <li><a href="#"> <i class="fab fa-google-plus-g"></i> </a></li>
                        </ul>
                    </div>
                </div><!-- //. single team member -->
            </div>
        </div>        
    </div>
</div>
<!-- team member area end -->
