<?php
    $this->mainMenu()->setActiveItemId('home');
    $this->headTitle('CTP-System');
?>    

<div class="">
    <h1 class="">Welcome to <span class="zf-green">CTP SYSTEM</span></h1>

    <p>
        Congratulations! You have successfully installed the <em><b>CTP SYSTEM APPLICATION </b></em> VER:<?= \Application\Module::VERSION?>         
    </p>
    
    <h3>WE ARE COMMITTED TO DELIVERING EXCELLENCE</h3>
    <p class="breadcrumb">
    Costex Tractor Parts CTP® is a worldwide quality supplier of New Replacement Parts for Caterpillar® and
    Komatsu® Equipment and Engines. At CTP, we not only o ffer you  premium parts  but  also an exceptional 
    service, outstanding savings and the support you need to get your order quickly and accurately. At CTP, 
    our focus is to provide you with great quality parts at a good value. Our new replacement parts undergo
    strenuous and strict inspection procedures to ensure the quality of  our product. Our basic  principle: 
    Quality with Value Guaranteed. Whether you are mining copper ore at high altitudes in the Chilean Andes,
    or digging an irrigation canal on the family farm, you can be rest assured that our whole team is 
    behind you every step of the way.              
    
        <a class="label label-success bottom-right" href="https://www.costex.com" target="_blank">Costex Online Site &raquo;</a>
    </p>
</div>

<div class="row"> 

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Inside Track</h3>
            </div>
            <div class="panel-body">
                <p>
                   The Insidetrack is a monthly publication that CTP creates and distributes to its customers in order to provide them with the latest information regarding new products, product improvements and industry news. Subscribe today.
                </p>

                <p><a class="" href="https://www.costex.com/insidetrack-index/" target="_blank">Explore ZF Modules &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">News &amp; Events</h3>
            </div>
            <div class="panel-body">
                <p>
                    Stay Informed with the Latest CTP News and Events.
                </p>

                <p><a class="" href="https://www.costex.com/news-and-events/" target="_blank">News &raquo;</a></p>
            </div>
        </div>
    </div>
</div>


