<?php
$this->headTitle('Settings');

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Settings'=>$this->url('application', ['action'=>'settings']),
            ]);

?>


<div class="row">
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading"> <span class="zf-green">Settings</span></div>            
            <div class="panel-body">
                <!-- P TAG: THERE ARE TWO BUTTONS -->
                <p>
                    <!-- BUTTON CHANGE PASSWORD -->
                    <a class="btn btn-warning" href="<?= $this->url('users',
                            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                        <span class="glyphicon glyphicon-asterisk"></span> Change Password
                    </a>    
                </p>        
                <table class="table table-striped table-bordered">
                     <tr class="info">
                        <th>ID:</th>
                        <td><?= $this->escapeHtml($user->getId()) ?></th>
                    </tr>
                    <tr>
                        <th>E-mail:</th>
                        <td><?= $this->escapeHtml($user->getEmail()) ?></th>
                    </tr>
                    <tr class="info">
                        <th>Full Name:</th>
                        <td><?= $this->escapeHtml($user->getFullName()) ?></th>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
                    </tr>
                </table>
            </div> <!-- panel-body -->
        </div> <!-- panel -->
    </div> <!-- col-md-6 -->
</div> <!-- row -->