<?php
    $this->headTitle('Settings');

    $this->mainMenu()->setActiveItemId('settings');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Settings'=>$this->url('application', ['action'=>'settings']),
                ]);

?>

<!------------------------------------- RENDERING HTML  --------------------------------------->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 single-service-item"> 
            <br>
            <table class="table table-striped border">
                 <tr class="info">
                    <th>ID</th>
                    <td><?= $this->escapeHtml( $user->getId() ) ?></td>
                </tr>
                <tr>
                    <th>E-MAIL</th>
                    <td><?= $this->escapeHtml($user->getEmail()) ?></td>
                </tr>
                <tr class="info">
                    <th>FULL NAME</th>
                    <td><?= $this->escapeHtml($user->getFullName()) ?></td>
                </tr>
                <tr>
                    <th>DATE CREATED</th>
                    <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
                </tr>
            </table>

            <!-- P TAG: THERE ARE TWO BUTTONS -->
            <div class="btn-wrapper">
                <!-- BUTTON CHANGE PASSWORD -->
                <a class="boxed-btn" 
                   href="<?= $this->url('users', ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                    CHANGE PWD                      
                </a>    
            </div> 
          
        </div> <!-- panel -->
    </div> <!-- col-md-6 -->
</div> <!-- row -->